### PR TITLE
Time class   jacob

### PR DESCRIPTION
**Pull request by philo-jh**
Wanting to merge completed Time.h &Time.cpp files with master.  Thanks for all the work, Armen!

### CODE REVIEW

**Comment by amourady** [comment]
@philo-jh Why do you want to merge it? The time class is already completed, to my knowledge.

**Comment by philo-jh** [comment]
My notes are on the site.

**Comment by Thblaauw** [comment]
Jacob, Time class is already completed

**Comment by philo-jh** [comment]
The Time class is not complete.  Did you guys test it?  At its current state, it cannot properly subtract (4PM - 2AM). Why? Because the current implementation works on a 10-base system (standard decimal), while universal time only has 0-23:99.  I have accounted for this logic.  Also, when you subtract 2 Times, when there is no date involved, you should NEVER get a negative number. It only makes sense to get a negative number when a date is involved.  I have accounted for this.

**Pull request closed without merging**
